### ISSUE TITLE
 Allow bgcolor for transparent png to jpg

### ISSUE THREAD

**Issue by lakano** [imazen/imageflow-node#10]
Hello,
Thanks for your work, we testing the imageflow-node since few days and seems the default background color for replacing transparency is still black.
On the imageflow repository, this have already been fixed ( https://github.com/imazen/imageflow/issues/175 ) to permit to choose a bgcolor, and to have white color by default, is it possible to do the same with the node package please?

**Comment by anshulrgoyal** [comment]
@lakano I updated the master will publish to NPM once the test passes.

**Comment by lilith** [comment]
Could you share the code you are using?

We have just released a new build of the Node package but it could take up
to 30 minutes to appear.

**Comment by anshulrgoyal** [comment]
Our release action failed on windows due to GitHub action `set-env` deprecation. I will first fix it and then release the package to npm

**Comment by anshulrgoyal** [comment]
@lakano Update NPM package.

**Comment by lakano** [comment]
Thanks for your reactivity !
I've just tested the rc13, but this still doesn't works in my case.

Here is my code, and to call it you need to run:
`node resize.js "http://www.libpng.org/pub/png/img_png/pnglogo--povray-3.7--black826--800x600.png" resized-{w}.jpg 0 150`


`const { MozJPEG, Steps, FromStream, FromFile, FromURL } = require('@imazen/imageflow')

class Resize extends Steps {

    resize(source, output, sizes) {
        const [ width, height ] = sizes[0].split('x')
        const out = output.replace('{w}', width).replace('{h}', height)
        const nextSizes = sizes.slice(1)

        this.branch((step) => {
            step.constrainWithin(width * 1, height * 1)
            if (nextSizes.length) {
                step.resize(source, output, nextSizes)
            }
            step.encode(new FromFile(out), new MozJPEG(100))
        })

        return this
    }
}


const start = async function()
{
    const [ src, out, min, max ] = process.argv.slice(2)
    const sizes = [
        '1920x1920',
        '1080x1080',
        '720x720',
        '480x480',
        '360x360',
        '120x120',
        '60x60',
    ]

    const input = src.indexOf('://') > -1 ? new FromURL(src) : new FromFile(src)
    for await (const size of sizes) {
        if (min || max) {
            const [ width, height ] = size.split('x')
            if ((min && width * 1 < min * 1)
            || (max && width * 1 > max * 1)) {
                continue
            }
        }
        console.log('size ' + size)
        await new Resize(input)
        .resize(src, out, [size])
        .execute()
    }
}

start()
`

**Comment by anshulrgoyal** [comment]
@lakano try using https://imazen.github.io/imageflow-node/classes/_json_.steps.html#constrain. It takes constrain class as the input you can change canvas color there.

**Comment by lilith** [comment]
This is fixed in Imageflow 1.5.3 https://github.com/imazen/imageflow/releases/tag/v1.5.3-rc57
I've added support for setting a matte (bgcolor) directly in the encoder and defaulted it to white. We'll have to add node bindings support for it though (https://github.com/imazen/imageflow-node/issues/12). I'd normally suggest using constraint.hints.background_color as a work around but that seems to be missing from the bindings (https://github.com/imazen/imageflow-node/issues/11)

**Comment by anshulrgoyal** [comment]
@lakano I fixed it on imageflow-node and will publish it once the test passes.

**Comment by anshulrgoyal** [comment]
@lakano Fixed it please try the newer version of `@imazen/imageflow`.

**Comment by lakano** [comment]
Well done ! It's fixed ! A very big THANK YOU for your reactivity, it's awesome !
